name: old-betsy
channels:
  - conda-forge
  - pytorch
dependencies:
  - aiohttp
  - aiofiles
  - dask
  - isort
  - requests
  - matplotlib >= 3.5.1
  - pydocstyle
  - pytest
  - pytest-cov
  - pep8-naming
  - pip
  - progress
  - python
  - pip >= 21.3.1
  - python >= 3.9
  - pandas >= 1.2.0
  - numpy >= 1.20.0
  - scipy >= 1.6.0
  - ipykernel >= 6.7.0
  - pydantic >= 1.8.2
  - python-dotenv >= 0.19.2
  - assertpy >= 1.1.0
  - black >= 22.1.0
  - pylint >= 2.12.2
  - python-dateutil >= 2.8.2
  - pytorch
  - torchtext
  - untangle